
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_FIRSTNAME VARCHAR(50),
    CUSTOMER_LASTNAME VARCHAR(50),
    CUSTOMER_TEL VARCHAR(30),
    CUSTOMER_EMAIL VARCHAR(50),
    CUSTOMER_ADDRESS VARCHAR(100)
)