USE SHARDING_DB2;
DROP TABLE IF EXISTS CUSTOMERS ;

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_FIRSTNAME VARCHAR(50),
    CUSTOMER_LASTNAME VARCHAR(50),
    CUSTOMER_TEL VARCHAR(30),
    CUSTOMER_EMAIL VARCHAR(50),
    CUSTOMER_ADDRESS VARCHAR(100)
);

insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Neile', 'Paolini', '7633962631', 'npaolini1e@cocolog-nifty.com', '6674 Alpine Place');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Pammi', 'Robion', '9633656019', 'probion1f@purevolume.com', '02 Dennis Road');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Julia', 'Housley', '8125185282', 'jhousley1g@sogou.com', '59 Evergreen Way');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Ardene', 'Hamor', '9031789929', 'ahamor1h@skyrock.com', '35 Scofield Plaza');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Niles', 'Rose', '7131546171', 'nrose1i@foxnews.com', '3 Anzinger Junction');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Issie', 'Stormouth', '7193224764', 'istormouth1j@canalblog.com', '17759 Straubel Place');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Heinrik', 'Kamall', '9017759772', 'hkamall1k@umich.edu', '80 Surrey Road');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Jorge', 'Tobias', '7232054147', 'jtobias1l@buzzfeed.com', '865 Westridge Pass');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Florie', 'Hubert', '3792811615', 'fhubert1m@rakuten.co.jp', '1 Dennis Plaza');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Anastassia', 'Gann', '3584161744', 'agann1n@unesco.org', '9 Vahlen Circle');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Marthena', 'Stansbie', '7048716587', 'mstansbie1o@goo.gl', '95041 Buhler Street');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Shaine', 'Lynde', '1427786283', 'slynde1p@slideshare.net', '5459 Scott Circle');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Caesar', 'Humpatch', '5793202008', 'chumpatch1q@shop-pro.jp', '3 Monterey Way');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Evonne', 'Couchman', '8602072685', 'ecouchman1r@state.gov', '4025 Springview Terrace');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Tim', 'Lavers', '1286470870', 'tlavers1s@pagesperso-orange.fr', '4 Hoffman Point');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Rori', 'Deverick', '5746990091', 'rdeverick1t@admin.ch', '985 Shopko Road');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Billye', 'Raoul', '1746418141', 'braoul1u@edublogs.org', '5636 Westridge Avenue');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Brantley', 'Jeaffreson', '5466479459', 'bjeaffreson1v@prlog.org', '9 Coolidge Terrace');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Chryste', 'Betho', '7073465638', 'cbetho1w@wunderground.com', '9325 Kenwood Park');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Joete', 'Horrigan', '7869952061', 'jhorrigan1x@lulu.com', '4 Mallard Pass');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Josephine', 'Coneau', '6398866135', 'jconeau1y@wufoo.com', '643 Starling Parkway');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Estele', 'Bonhill', '5726775440', 'ebonhill1z@yale.edu', '71 Chinook Center');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Levy', 'Sommerlin', '7621706928', 'lsommerlin20@hubpages.com', '9895 Evergreen Parkway');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Odelinda', 'Barette', '5405880853', 'obarette21@bbc.co.uk', '74924 Erie Street');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Janina', 'Kissell', '7038678061', 'jkissell22@imdb.com', '31 Delaware Court');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Bethina', 'Leinster', '5083486510', 'bleinster23@4shared.com', '2 Division Avenue');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Gun', 'Gligorijevic', '3623935757', 'ggligorijevic24@devhub.com', '40265 Basil Court');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Jackie', 'Druhan', '4636931222', 'jdruhan25@patch.com', '6731 Talmadge Way');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Estrellita', 'Riteley', '1433318047', 'eriteley26@so-net.ne.jp', '9 Dunning Circle');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Jeromy', 'Botham', '9607373481', 'jbotham27@furl.net', '1706 Artisan Road');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Viviana', 'Wales', '3533170746', 'vwales28@flavors.me', '09878 Longview Avenue');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Austin', 'Kemston', '5113466470', 'akemston29@wired.com', '54 Continental Place');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Georgeanne', 'Takkos', '8622451234', 'gtakkos2a@wired.com', '16275 Kensington Drive');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Tiffy', 'March', '3234334092', 'tmarch2b@washingtonpost.com', '9 Dryden Hill');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Doloritas', 'Kings', '4713466237', 'dkings2c@smugmug.com', '2 Everett Pass');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Zared', 'Shepherd', '9926582735', 'zshepherd2d@bizjournals.com', '39978 Toban Place');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Josee', 'Myderscough', '3199680532', 'jmyderscough2e@simplemachines.org', '78988 Doe Crossing Pass');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Leonard', 'Callway', '2822938273', 'lcallway2f@yellowbook.com', '82 Independence Drive');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Rhetta', 'Wykes', '1771705340', 'rwykes2g@pbs.org', '156 Almo Point');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Cammi', 'Munning', '5234389921', 'cmunning2h@bluehost.com', '67 Carberry Park');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Natassia', 'Dinning', '6283235002', 'ndinning2i@statcounter.com', '65331 Almo Alley');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Elyn', 'Harberer', '1271902144', 'eharberer2j@admin.ch', '8 Linden Terrace');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Catha', 'Aujouanet', '2238742423', 'caujouanet2k@arstechnica.com', '478 Loomis Circle');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Alf', 'Alldred', '9312539215', 'aalldred2l@gov.uk', '7012 Anthes Parkway');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Jerrome', 'Ingre', '5309210925', 'jingre2m@mashable.com', '09016 Heath Center');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Daven', 'Lillywhite', '7763400570', 'dlillywhite2n@nps.gov', '9165 Corry Junction');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Hope', 'Sheringham', '1488489002', 'hsheringham2o@1688.com', '37 Main Crossing');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Loren', 'Kenvin', '9317956572', 'lkenvin2p@tiny.cc', '022 Bonner Trail');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Nappie', 'Wreight', '9673659774', 'nwreight2q@home.pl', '7 Banding Court');
insert into CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS) values ('Cornelia', 'Gallego', '1462820107', 'cgallego2r@sphinn.com', '4 Hooker Drive');



INSERT INTO SHARDING_DB2.CUSTOMERS (CUSTOMER_FIRSTNAME, CUSTOMER_LASTNAME, CUSTOMER_TEL, CUSTOMER_EMAIL, CUSTOMER_ADDRESS)values ('Admin', 'Testing', '1234567889', 'bot-duck', '123 ABC street, Toronto, Canada');UPDATE CENTRAL_SHARDING.DETAILS SET RECORDS = RECORDS + 1 WHERE SHARD_NAME = 'SHARDING_DB2';
